### ISSUE TITLE
[Feature] Consider a sub-project to provide user/team/project abstraction

### ISSUE THREAD

**Issue by resouer** [kubevela/kubevela#1416]
**Is your feature request related to a problem? Please describe.**

Consider a plugin in KubeVela that provides abstraction of user/team/project out-of-box, configurable by CRD and integrated with authz add-ons by default.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
I think there're many questions on this issue here:

1. What's the relationship between user/team with the project we're planning to design? Do you mean there're admin and normal user? The admin could create a team and then,
2. What kind of authorization do we want to privilege to the normal user that differ from the admin?
3. Will a user have different teams？ Does projects in a team in different K8s namespaces or in the same? 
4. What kind of RBAC should we configure for admin and normal user?

**Comment by resouer** [comment]
xref: https://github.com/sighupio/permission-manager

**Comment by wonderflow** [comment]
implemented in velaux https://github.com/kubevela/velaux
