### ISSUE TITLE
[Feature]  Use ArgoCD to delivery helm type component

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#3229]
**Is your feature request related to a problem? Please describe.**

Currently based `fluxcd` addon have many problems

1. such as too many crds and controllers, which due to fluxcd addon install failed too often.
2. applied resources have been recorded in `helmRelease`'s status.
3. hasn't support oci-registry helm repo

So I proposal make an argocd addon to let user choose use argo or flux to solve deliver helm component.

**Describe the solution you'd like**

we should make an 'argocd' addon to solve these problems. https://argo-cd.readthedocs.io/en/stable/

1.  argocd addon should not rely-on fluxcd addon, so we need generate out all manifest from helm chart
2. need prepare a argocd's application defintion

 
**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Currently, argocd addon has been supported: https://github.com/kubevela/catalog/tree/master/experimental/addons/argocd

The helm component definition has the same spec with fluxcd.

The only thing we need to resolve is the dependency in addon that we should support dependsOn definition instead of specified another addon name.
