### ISSUE TITLE
[Feat] rollout trait can be controllered in hubcluster

### ISSUE THREAD

**Issue by oeular** [kubevela/kubevela#3559]
# Goal
    - CRs related vela can be managed in HubCluster
    - No CRs are needed to be in ManagedClusters，so that they can be easy and clean for future maintaining and upgrading
# Solution
  -  trait CRs installled, deployed and managed in hubcluster
  -  trait Controller running in hubcluster

**Comment by oeular** [comment]
# Advantage：
   - Keep managedclusters to be tiny and enough original for future upgrading and maintaining
   - Managing vela and related CRDs，CRs and Controllers can be unified in hubcluster
   - Extending managedclusters for app deloyment can be more smooth
   - Most importantly，other similar CRs will be used，so this problem is common for them

**Comment by fourierr** [comment]
This feature enables that trait's CRs can be deployed on hubcluster conviently and CR was reconciled on hubcluster directly

**Comment by barnettZQG** [comment]
@oeular thanks for your proposal, you need a rollout controller working on multiple managed clusters. it needs to watch resource events from multiple managed clusters. please let us know your thoughts about the following:

1. The vela rollout cannot work in this case, are you providing a new implementation?
2. There are some rollout implementations in the community, ArgoRollout、KruiseRollout, and Flagger, all work in one cluster.
3. Do we need to implement A/B? how to adjust the traffic of different clusters, maybe there are different ingress controllers.
4. Watch and handle events on multiple remote networks, how to ensure performance.

**Comment by wonderflow** [comment]
@oeular Can you provide some design about the Implementation ? AFAIK, this won't be easy, it's not supported by the framework now.

**Comment by zmberg** [comment]
We can draw an analogy between:
1. vela application vs deployment 
2. vela application vs rollout

The vela application has a full amount of data (including deployment and rollout configuration) in the control cluster, which is distributed by the vela to the subclusters and consumed by the respective controllers (rollout, deployment), after which the status data is synchronized by the vela back to the control cluster.

And after thinking about the rollout, it will be very difficult to put it into the control cluster, because it will be more difficult to operate the dpeloyment of multiple subclusters at the same time.

[kruise rollout](https://github.com/openkruise/rollouts) is a rollout project **built by kruise and the vela community**. From the user's point of view, as long as the application is configured on the control cluster, vela can be responsible for sending the configuration to the subclusters, and the rollout can work with deployment in the subclusters.

kruise rollout currently supports canary release and batch release, and will implement metrics analysis, hook mechanism, A/B Test and many other capabilities in the future.

**Comment by wangyikewxgm** [comment]
This the rollout trait work in hubCluster it should understand all multi-cluster info defined in application, and handle rollout all workloads in all managedClusters. This will break our framework that only app-controller can touch the managedClusters.

**Comment by oeular** [comment]
@zmberg thanks for your solution, kruise rollout is a nice choice, we will consider  in some days. But now we  mostly want to  choose k8s deployment for implementing our rollout trait. So kruise rollout solution can be applied to k8s deployment.

**Comment by oeular** [comment]
@wonderflow  OK，we will try to give a proposal soon

**Comment by oeular** [comment]
@wangyikewxgm  only app-controller can touch the mngedclusters，it means ONLY app-controller can track k8s objects? Other controller ONLY control its CRs (not buitl-in k8s objects) in mngedclusters or hubcluster？

**Comment by zmberg** [comment]
> @zmberg thanks for your solution, kruise rollout is a nice choice, we will consider in some days. But now we mostly want to choose k8s deployment for implementing our rollout trait. So kruise rollout solution can be applied to k8s deployment.

Kruise Rollout can be applied to k8s deployment workload now. refer: https://github.com/openkruise/rollouts/blob/master/docs/tutorials/basic_usage.md

**Comment by oeular** [comment]
@zmberg  Thanks. The key point, all CRDs and CRs of kruise rollout  can be managed in HubCluster ? Or there is any solution for this.

**Comment by tangoliu** [comment]
@barnettZQG @zmberg  Can resources be deployed to HubCluster or ManagedClusters through cluster gateway adaptation.

**Comment by wonderflow** [comment]
> We may extend a new policy type named policy2trait

How does this policy work in this case?

**Comment by fourierr** [comment]
This feat is handled by https://github.com/kubevela/kubevela/pull/3774
