### ISSUE TITLE
More status 'vela addon ls', and add 'vela addon fluxcd log' to check if addon is really started, failed, what is error[Feature]

### ISSUE THREAD

**Issue by jinnjwu** [kubevela/kubevela#3856]
**Is your feature request related to a problem? Please describe.**
When we run vela addon ls,  output only showing enabled, acuttally, addon is not started successfully backend, we would like to request more status on 'vela addon ls', and can print log on that.
From below log, it shows successfully, but backend fluxcd is not started 

vela addon enable fluxcd/
enable addon by local dir: fluxcd/
I0510 22:35:40.751318   22960 apply.go:107] "patching object" name="config-helm-repository" resource="core.oam.dev/v1beta1, Kind=ComponentDefinition"
I0510 22:35:40.900227   22960 apply.go:107] "patching object" name="helm" resource="core.oam.dev/v1beta1, Kind=ComponentDefinition"
I0510 22:35:41.155116   22960 apply.go:107] "patching object" name="kustomize-json-patch" resource="core.oam.dev/v1beta1, Kind=TraitDefinition"
I0510 22:35:41.311608   22960 apply.go:107] "patching object" name="kustomize-patch" resource="core.oam.dev/v1beta1, Kind=TraitDefinition"
I0510 22:35:41.461774   22960 apply.go:107] "patching object" name="kustomize" resource="core.oam.dev/v1beta1, Kind=ComponentDefinition"
I0510 22:35:41.616520   22960 apply.go:107] "patching object" name="kustomize-strategy-merge" resource="core.oam.dev/v1beta1, Kind=TraitDefinition"
I0510 22:35:41.822288   22960 apply.go:107] "patching object" name="component-uischema-helm" resource="/v1, Kind=ConfigMap"
I0510 22:35:42.033250   22960 apply.go:107] "patching object" name="addon-secret-fluxcd" resource="/v1, Kind=Secret"
Addon: fluxcd enabled Successfully.
Please access the fluxcd from the following endpoints:
+---------+-----------+--------------------------+----------+
| CLUSTER | COMPONENT | REF(KIND/NAMESPACE/NAME) | ENDPOINT |
+---------+-----------+--------------------------+----------+
+---------+-----------+--------------------------+----------+

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyikewxgm** [comment]
The reason is components  of fluxcd addon is `k8s-objects`, this type of component cannot check the status ready.I think we can introduce a component type like `controller` witch means a backend long-running worker but needn't expose service, then configure the health check status.

**Comment by wangyikewxgm** [comment]
We can use the `worker` to implement the fluxcd's controller component type.

**Comment by StevenLeiZhang** [comment]
my proposal:
 let "vela addon status xxx" print the Application name of this addon, then user could execute " vela -n vela-system status xxxx" to show more details

**Comment by wangyikewxgm** [comment]
> my proposal: let "vela addon status xxx" print the Application name of this addon, then user could execute " vela -n vela-system status xxxx" to show more details

Yes the current logic is just like this. But the  `helm-release controller` of fluxcd addon is applied by `k8s-objects` component, and this type component cannot wait unit all the pods are ready. So we should change it to `worker` component.

**Comment by charlie0129** [comment]
After experimenting with a prototype (`fluxcd` addon with `worker` component), we think this would cause a breaking change (due to how addons work currently), which is not ideal for users.

Using a breaking change to fix this issue is probably not worth it.

If the addon mechanism allows us to fix this issue without breaking changes in the future, we can start fixing this again.

<details>

The components in an addon can only be installed in `vela-system` namespace currently. However, `fluxcd` is installed in `flux-system` (which is possible using raw yaml, unlike components), which means we need to move all `fluxcd` controllers to `vela-system` namespace. 
I have tried this. It worked well, and solved this issue. 
But old users are used to diagnose `fluxcd` controller issues in the `flux-system` namespace, this namespace change can cause inconvenience for them, hence a breaking change.
</details>
