### ISSUE TITLE
[Feature] Upgrade golangci-lint to a higher version

### ISSUE THREAD

**Issue by FogDong** [kubevela/kubevela#4018]
**Is your feature request related to a problem? Please describe.**

The golangci-lint in KubeVela repo is `v1.38.0` which is kinda outdated, it's nice to upgrade it to a higher version.

At the same time, some codes in the repo don't meet the lint requirement in the higher version, so please fix them in the upgrading.

You can use the command `make lint` to check all the results.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Along with the upgrade, we should fix the potential lints detected in the new version.

**Comment by FogDong** [comment]
> @FogDong `make lint` has errors now, am i right? I forked your repository, and when i `make lint`, i got some errors

If your `golangci-lint` is higher than `v.1.38.0`, the code won't pass all the lints.

So yes if you want to get started with this issue, you can fix all the lints problem when you use a higher version of `golangci-lint`.

**Comment by MimicTester1307** [comment]
@FogDong One of the checks from `golangci-lint`  states that `strings.Title`  has been deprecated. It suggests using [cases]( golang.org/x/text/cases instead).

However, `cases.Title` requires a language tag to specify which language it should parse. I used English at first, but since KubeVela is used in Chinese, I may have to check for that too. This could mean modifying function parameters, which I am skeptical about.  What do you suggest? Should I just use English for now?

Please find attached a working sample code I wrote on the Go playground

![Screenshot from 2022-07-14 14-29-31](https://user-images.githubusercontent.com/57713506/179006824-23c2641f-44e8-4a33-8178-606ae4402b8c.png)

**Comment by FogDong** [comment]
>  Should I just use English for now?

@MimicTester1307 You can use English directly, some of the core contributors of KubeVela are from China but they're all good with both English and Chinese, the project itself is a worldwide project so we can just use English in the code.

**Comment by wonderflow** [comment]
This issue is not concrete and actually it can be never closed if it's really an issue, because we can always upgrade to higher version as time passed. 😸  Closing
