### ISSUE TITLE
vela show --web not populating ComponentType

### ISSUE THREAD

**Issue by farhaan-shamsee** [kubevela/kubevela#5769]
**Describe the bug**

The command `vela show --web` runs successfully, but the `Component Types` does not populated. The `trait`, `workflow steps` and `Policies `get populated properly. 

The command works properly on K8s version `1.24`, but not on `1.25` and `1.26`

When the command vela show is ran it generates the documentation, in that under _.vela/reference/docs_ the folder componentDefinition has all the contents but the `_sidebar.md` does not have anything under - Components Types

**To Reproduce**

run command `vela show --web`

**Expected behavior**

Component definitions should get populated under `Components Types` drop down menu.

**Screenshots**
![vela_browser_snip](https://user-images.githubusercontent.com/77592635/228462569-342db8b3-5817-48ce-9bd9-eda2a2a8ff07.png)
![vela_sidebar_snip](https://user-images.githubusercontent.com/77592635/228462545-06790eca-29fd-40ea-9379-4dd7a86b6ab7.png)

**KubeVela Version**

CLI Version: 1.7.3
Core Version: 1.7.3
GitRevision: git-f49f11dd
GolangVersion: go1.19.5

**Cluster information**

Kubernetes Version 1.26

**Additional context**

[Slack thread](https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1679920296143119)

**Comment by rhzx3519** [comment]
@farhaan-shamsee @chivalryq  I have located the code line causing this error. https://github.com/kubevela/kubevela/blob/master/references/docgen/cluster.go#L170

I guess in Kubernetes 1.25.0 and above, CronJob's version is v1 instead of v1beta1. This caused a mismatch between Cluster and KubeVela. The CronJob's version in KubeVela is still v1beta1.

<img width="1268" alt="Screenshot 2023-03-30 at 12 19 39 am" src="https://user-images.githubusercontent.com/7357472/228554349-c7f17ff4-f325-4e45-b0bd-155227359662.png">

**Comment by chivalryq** [comment]
@rhzx3519 PR is always welcome! Please keep the compatibility of v1beta1 CronJob

**Comment by rhzx3519** [comment]
Hi @chivalryq , after reading related codes, I guess the reason is that the ComponentDefinition - cron-task - workload CronJob's version is hard-coded in the original cue file. The manifest generation process is .cue files, helm templates, and kubernetes manifests. Do you have any idea about how to set the CronJob version based on kubernetes version?

**Comment by chivalryq** [comment]
I think this is fixed by #5800 
![image](https://github.com/kubevela/kubevela/assets/47812250/6d43fbe2-e91c-4581-a19a-36ff1ccc8832)
