### ISSUE TITLE
[Feature] Don't need install CRD on HubCluster for customized Component/Trait

### ISSUE THREAD

**Issue by StevenLeiZhang** [kubevela/kubevela#5973]
**Is your feature request related to a problem? Please describe.**

When use customized Component or Trait, if it consists of CRD, Kubevela need the CRD exists in HubCluster.
For example. OpenYurt is a kind of Edge solution, its workload is only useable on edge member cluster. If I package YurtAppSet to be Vela Component, YurtAppset CRD has to be intatalled to HubCluster. For that, I have to rebuild the helm chart of OpenYurt.

It is better to remove this restriction, then only need install YurtAppset CRD and controller to member cluster.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sbdtu5498** [comment]
@StevenLeiZhang correct me if I am wrong, but you want such a feature because of the fact that it would cost too much for the hub cluster to hold CRD for each edge node as OpenYurt requires different configurations for different edge clusters. So from what I think, would a simple crdLocation spec addition be enough for your use case? From what I understood, controllers are deployed in the managed cluster. And By having such spec in the application CRD you can also ensure that CRDs are also being installed in the managed cluster rather than the hub one.

**Comment by StevenLeiZhang** [comment]
> @StevenLeiZhang correct me if I am wrong, but you want such a feature because of the fact that it would cost too much for the hub cluster to hold CRD for each edge node as OpenYurt requires different configurations for different edge clusters. So from what I think, would a simple crdLocation spec addition be enough for your use case? From what I understood, controllers are deployed in the managed cluster. And By having such spec in the application CRD you can also ensure that CRDs are also being installed in the managed cluster rather than the hub one.



In general, addon must be installed to Member Cluster。 I think we don't need add new field in spec.
The Application defines Topology Policy to describe deployment target cluster, since the addon must be installed in the Member cluster, we need parse Topology Policy and retrieve CRD schema from the member cluster before rendering Component and Trait.

**Comment by sbdtu5498** [comment]
@StevenLeiZhang I need a bit more clarification on this. When I asked about adding a location spec, what I mean is adding a crdLocation spec in topology that would point out the cluster location in which the CRD is deployed. Then KubeVela can interact with the API of that cluster to fetch the CRD schema. Of course, in this situation, you would need to deploy the CRD beforehand so that it can be fetched. And in a default scenario, when you would not provide crdLocation, KubeVela would try to fetch the CRD schema from the hub cluster API and if not found in both cases, it would throw an error. Now, this way, previous functionalities would remain attached and your task might be done, thus it wouldn't break KubeVela's existing API as well. Now if I have made some mistake in understanding the issue, correct me.

**Comment by sbdtu5498** [comment]
@wangyikewxgm I wasn't able to attend the KubeVela meeting, If possible can you please provide anything important that was discussed that I might take into consideration while designing the solution?

**Comment by Somefive** [comment]
@sbdtu5498 As we have discussed on the community meeting, we would prefer not exposing extra fields to let users configure and the CRD should go to the place where user actually needed. I am also looking into this technical issue.

**Comment by sbdtu5498** [comment]
@Somefive how about not adding crdLocation spec, but rather using the existing topology field to check into the tagged managed cluster's API server to find CRD schema before looking into the hub cluster's API server for CRD schema?

**Comment by Somefive** [comment]
> @Somefive how about not adding crdLocation spec, but rather using the existing topology field specs to check into the tagged managed cluster's API server to find CRD schema before looking into the hub cluster's API server for CRD schema?

In my opinion, I think this is a low layer issue and not directly related to application itself. It should not use the topology to discover CRDs but instead it should use the request cluster to discover (which is indirectly indicated by the topology but there are also cases that topology is not used but multicluster request is made).

**Comment by sbdtu5498** [comment]
@Somefive I see. I was thinking of taking an approach where KubeVela CRDs would still be deployed in the hub cluster but the external CRDs that are required by the customized components and traits, for example, OpenYurt CRDs can be fetched from the managed cluster pointed out by some means such as topology field, etc. Is your approach somewhat related to allowing KubeVela CRDs to be deployed directly on the cluster on which we want to deploy other CRDs and deployments?  Also, can you give me a few examples where the request cluster is being discovered without the help of the topology field in the case of a multicluster scenario? And correct me If I have still got the situation incorrectly.

**Comment by Somefive** [comment]
> @Somefive I see. I was thinking of taking an approach where KubeVela CRDs would still be deployed in the hub cluster but the external CRDs that are required by the customized components and traits, for example, OpenYurt CRDs can be fetched from the managed cluster pointed out by some means such as topology field, etc. Is your approach somewhat related to allowing KubeVela CRDs to be deployed directly on the cluster on which we want to deploy other CRDs and deployments? Also, can you give me a few examples where the request cluster is being discovered without the help of the topology field in the case of a multicluster scenario? And correct me If I have still got the situation incorrectly.

So with the Pull Request I raised, it is possible for user to **ONLY** install OpenYurt CRD in one managed cluster and then create an application that delivers the OpenYurt resource to that cluster, without any extra configuration.

**Comment by sbdtu5498** [comment]
@Somefive I see! Thanks a lot for the explanation.
/unassign.
