### ISSUE TITLE
FLUXCD  BOOTUP FAILED IN 1.9.2

### ISSUE THREAD

**Issue by karl-chanel** [kubevela/kubevela#6171]
**Describe the bug**

FLUXCD ENABLING FAILED IN 1.9.2

**Comment by karl-chanel** [comment]
![屏幕截图 2023-07-01 144121.png](https://github.com/kubevela/kubevela/assets/78248702/84611735-ec0d-4cfe-aa67-06a861808c3d)

![屏幕截图 2023-07-01 144055.png](https://github.com/kubevela/kubevela/assets/78248702/7d2a34b4-9c32-4f51-8a31-42ad716d96ce)

**Comment by wonderflow** [comment]
dup with

https://github.com/kubevela/kubevela/issues/6166

https://github.com/kubevela/kubevela/issues/6150

**Comment by karl-chanel** [comment]
![屏幕截图 2023-07-04 153926.png](https://github.com/kubevela/kubevela/assets/78248702/8f1be60a-ecf2-4e0d-8255-bfb6a39e11ed)

**Comment by karl-chanel** [comment]
Hey, I tried the latest 1.9.3, It is still not working like above

**Comment by wonderflow** [comment]
@karl-chanel can you show me the `vela version` result to check if you're using v1.9.3

**Comment by karl-chanel** [comment]
![屏幕截图 2023-07-04 173426.png](https://github.com/kubevela/kubevela/assets/78248702/cdb1198d-2a2b-4fe5-95f8-7201999d45b6)

![屏幕截图 2023-07-04 173530.png](https://github.com/kubevela/kubevela/assets/78248702/7a49edc8-ebd0-4338-af81-6816e968993c)

@wonderflow

**Comment by wonderflow** [comment]
@karl-chanel Thanks, did you try delete the crd and uninstall the addon before retry?

Uninstall fluxcd addon by:

```
 vela addon disable fluxcd
```

You need to delete CRD by:

```
kubectl get crd -l "app.kubernetes.io/part-of=flux" -o name | xargs kubectl delete
```

**Comment by karl-chanel** [comment]
![屏幕截图 2023-07-04 195257.png](https://github.com/kubevela/kubevela/assets/78248702/6a77777b-9d51-4c68-bb7c-899931d52571)
thanks  It works fine now, So when kubevela update via helm, the crd ain't update automatically?

**Comment by wonderflow** [comment]
@karl-chanel Let me clarify:

1. Helm Chart won't update the CRD
2. The fluxcd addon has no relation with helm chart, we embed crd inside vela application as components. 
 
When fluxcd addon update, it will update the crd. But this bug is due to update the status of CRD according to https://github.com/kubevela/kubevela/pull/6182 . When you update fluxcd or vela-core, no mechanism will remove the updated status, so it rely on a manual delete or update. Just like the operations you did.
