### ISSUE TITLE
[FEATURE] Is kubevela dead?

### ISSUE THREAD

**Issue by hprotzek** [kubevela/kubevela#6449]
Hi there, looking at the commits in the last 6 month and the documentation roadmap, which was updated the last time in June 2023, I am wondering if this projects got abandoned from Alibaba?

I was already asking this question last year in the slack channel and the answer was, the developers just got assigned to another project and they will pick up kubevela after that again? If this is the case, could you please give an update on the roadmap Alibaba has with this project?

**Comment by wonderflow** [comment]
Hi @hprotzek ! You've been a valued friend to KubeVela since its early adoption days, and we appreciate your continuous support and watchful eye on the project. While I'm not currently able to speak on behalf of Alibaba, I am aware that the project continues to hold value for them, and they are actively evaluating the next steps. I remain optimistic that there will be positive developments and more contributions from Alibaba in the near future.

Furthermore, KubeVela is a CNCF project, and community maintainers continue to actively invest their time in its upkeep. As one of the maintainers, I encourage everyone interested in this project to join us, contribute actively, and become a new maintainer.

**Comment by geffzhang** [comment]
https://github.com/radius-project/radius  seems to be an alternative project to Kubevela, which is developing rapidly and there are cases of substitution https://blog.radapp.io/posts/2023/12/06/case-study-how-millennium-bcp-leverages-radius/
